[book]
title       = "Cinnabar"
description = "The Cinnabar Verilog/SystemVerilog/VHDL model compiler and simulation engine"
authors     = [
	"Aki Van Ness"
]
language    = "en"
src         = "src"

[build]
build-dir = "../../target/book/cinnabar"

[output.html]
default-theme        = "dark"
preferred-dark-theme = "coal"
smart-punctuation    = false
git-repository-url   = "https://codeberg.org/shrine-maiden-heavy-industries/Vermilion"
git-repository-icon  = "fab-git-alt"
edit-url-template    = "https://codeberg.org/shrine-maiden-heavy-industries/Vermilion/_edit/main/docs/cinnabar/{path}"

[preprocessor]
