-- SPDX-License-Identifier: BSD-3-Clause
--
-- This file is part of the IEEE 1076-2019 VHDL standard library provided
-- by [Vermilion] as a supplementary file for VHDL support.
--
-- NOTE: This file is API compatible with, but not a direct verbatim copy of the definition
-- as noted in IEEE 1076-2019.
--
-- [Vermilion]: https://github.com/shrine-maiden-heavy-industries/Vermilion
--
