[book]
title       = "Vermilion"
description = "The Vermilion Verilog, Verilog-AMS, SystemVerilog, VHDL, and VHDL-AMS Language Server, Linter, and Formatter"
authors     = [
	"Aki Van Ness"
]
language    = "en"
src         = "src"

[build]
build-dir = "../../target/book/vermilion"

[output.html]
default-theme        = "dark"
preferred-dark-theme = "coal"
smart-punctuation    = false
git-repository-url   = "https://codeberg.org/shrine-maiden-heavy-industries/Vermilion"
git-repository-icon  = "fab-git-alt"
edit-url-template    = "https://codeberg.org/shrine-maiden-heavy-industries/Vermilion/_edit/main/docs/vermilion/{path}"

[preprocessor]
