-- SPDX-License-Identifier: BSD-3-Clause
--
-- This file is part of the IEC 61691-1-1:2011 VHDL standard library provided
-- by [Vermilion] as a supplementary file for VHDL support.
--
-- NOTE: This file is API compatible with, but not a direct verbatim copy of the definition
-- as noted in IEC 61691-1-1:2011.
--
-- [Vermilion]: https://github.com/shrine-maiden-heavy-industries/Vermilion
--
