[book]
title       = "Mercurous"
description = "HDL agnostic simulator control and transport protocol"
authors     = [
	"Aki Van Ness"
]
language    = "en"
src         = "src"

[build]
build-dir = "../../target/book/mercurous"

[output.html]
default-theme        = "dark"
preferred-dark-theme = "coal"
smart-punctuation    = false
git-repository-url   = "https://codeberg.org/shrine-maiden-heavy-industries/Vermilion"
git-repository-icon  = "fab-git-alt"
edit-url-template    = "https://codeberg.org/shrine-maiden-heavy-industries/Vermilion/_edit/main/docs/mercurous/{path}"

[preprocessor]
